[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xser"
version = "2026.0.0"
description = "jaX SERializer (XSER)"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
  { name = "Jungho Mun", email = "mjh92@postech.ac.kr" }
]
keywords = ["xser"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
  "jax",
  "jaxlib",
  "numpy",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.0",
]

[project.scripts]
xser = "xser.__main__:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]

[project.urls]
Homepage = "https://github.com/j-mun/xser"
Repository = "https://github.com/j-mun/xser"